//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFacilitesSystemEntities : DbContext
    {
        public DbFacilitesSystemEntities()
            : base("name=DbFacilitesSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Place_Area_> Tbl_Place_Area_ { get; set; }
        public virtual DbSet<Tbl_Place_Assignment> Tbl_Place_Assignment { get; set; }
        public virtual DbSet<Tbl_Place_AssignmentRequests> Tbl_Place_AssignmentRequests { get; set; }
        public virtual DbSet<Tbl_Place_Code> Tbl_Place_Code { get; set; }
        public virtual DbSet<Tbl_Place_Diagram> Tbl_Place_Diagram { get; set; }
        public virtual DbSet<Tbl_Place_Subarea> Tbl_Place_Subarea { get; set; }
        public virtual DbSet<Tbl_Place_TypePlace> Tbl_Place_TypePlace { get; set; }
        public virtual DbSet<Tbl_Place_UserRoles> Tbl_Place_UserRoles { get; set; }
        public virtual DbSet<Tbl_Place_Users> Tbl_Place_Users { get; set; }
        public virtual DbSet<Tbl_Place_UserStatus> Tbl_Place_UserStatus { get; set; }
    }
}
