//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Place_Assignment
    {
        public int id_assignment { get; set; }
        public int id_code { get; set; }
        public int id_user { get; set; }
    
        public virtual Tbl_Place_Code Tbl_Place_Code { get; set; }
        public virtual Tbl_Place_Users Tbl_Place_Users { get; set; }
    }
}
