//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Place_Diagram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Place_Diagram()
        {
            this.Tbl_Place_Code = new HashSet<Tbl_Place_Code>();
        }
    
        public int id_diagram { get; set; }
        public int id_area { get; set; }
        public Nullable<int> id_subarea { get; set; }
        public Nullable<int> piso_snorkel { get; set; }
        public Nullable<int> size_x { get; set; }
        public Nullable<int> size_y { get; set; }
        public string data_info { get; set; }
    
        public virtual Tbl_Place_Area_ Tbl_Place_Area_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_Code> Tbl_Place_Code { get; set; }
        public virtual Tbl_Place_Subarea Tbl_Place_Subarea { get; set; }
    }
}
