//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Place_Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Place_Code()
        {
            this.Tbl_Place_Assignment = new HashSet<Tbl_Place_Assignment>();
            this.Tbl_Place_AssignmentRequests = new HashSet<Tbl_Place_AssignmentRequests>();
        }
    
        public int id_code { get; set; }
        public int id_diagram { get; set; }
        public string data_coord { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> type_place { get; set; }
        public string chair_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_Assignment> Tbl_Place_Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_AssignmentRequests> Tbl_Place_AssignmentRequests { get; set; }
        public virtual Tbl_Place_Diagram Tbl_Place_Diagram { get; set; }
        public virtual Tbl_Place_TypePlace Tbl_Place_TypePlace { get; set; }
    }
}
