//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Place_Subarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Place_Subarea()
        {
            this.Tbl_Place_Diagram = new HashSet<Tbl_Place_Diagram>();
        }
    
        public int id_subarea { get; set; }
        public string name_subarea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_Diagram> Tbl_Place_Diagram { get; set; }
    }
}
