//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLugaresFacilities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Place_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Place_Users()
        {
            this.Tbl_Place_Assignment = new HashSet<Tbl_Place_Assignment>();
            this.Tbl_Place_AssignmentRequests = new HashSet<Tbl_Place_AssignmentRequests>();
        }
    
        public int id_users { get; set; }
        public string id_employee { get; set; }
        public int id_rol { get; set; }
        public int id_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_Assignment> Tbl_Place_Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Place_AssignmentRequests> Tbl_Place_AssignmentRequests { get; set; }
        public virtual Tbl_Place_UserRoles Tbl_Place_UserRoles { get; set; }
        public virtual Tbl_Place_UserStatus Tbl_Place_UserStatus { get; set; }
    }
}
